name : Jett Whitakers Portfolio
brand : Jett Whitaker
description : Jett Whitakers Personal Portfolio
keyword :
url : https://beta.jettwhitaker.com
email : jett@jettwhitaker.com
github : jettw
author : Jett Whitaker
year : 2016
markdown : kramdown
exclude :
  - node_modules
